name: Build Windows Installer
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the application
        run: |
          pip install pyinstaller
          pyinstaller --onefile src/ms2_main.py --icon src/assets/app_icon.ico

      - name: Create zip archive
        run: |
          cd dist
          tar -a -c -f streamlit_app.zip *

      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: streamlit_app
          path: dist/streamlit_app.zip